
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 25 18:24:22 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;

/** CUP v0.10k generated parser.
  * @version Sun Jan 25 18:24:22 CET 2026
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\042\000\002\002\004\000\002\024\002\000\002\003" +
    "\007\000\002\025\002\000\002\004\007\000\002\005\004" +
    "\000\002\005\002\000\002\006\005\000\002\006\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\007\004\000\002\007\002\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\011\006" +
    "\000\002\012\010\000\002\013\010\000\002\017\003\000" +
    "\002\017\002\000\002\016\005\000\002\016\003\000\002" +
    "\020\005\000\002\020\007\000\002\014\007\000\002\022" +
    "\003\000\002\022\002\000\002\021\005\000\002\021\003" +
    "\000\002\023\003\000\002\023\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\072\000\004\004\005\001\002\000\004\002\074\001" +
    "\002\000\004\022\006\001\002\000\004\020\000\001\002" +
    "\000\004\020\010\001\002\000\016\006\ufffe\007\ufffe\010" +
    "\ufffe\020\ufffe\021\ufffe\022\ufffe\001\002\000\004\005\012" +
    "\001\002\000\004\002\uffff\001\002\000\016\006\ufffb\007" +
    "\ufffb\010\ufffb\020\ufffb\021\ufffb\022\ufffb\001\002\000\016" +
    "\006\022\007\020\010\021\020\ufff4\021\ufff4\022\ufff4\001" +
    "\002\000\016\006\ufffc\007\ufffc\010\ufffc\020\ufffc\021\ufffc" +
    "\022\ufffc\001\002\000\004\022\055\001\002\000\016\006" +
    "\ufff9\007\ufff9\010\ufff9\020\ufff9\021\ufff9\022\ufff9\001\002" +
    "\000\012\011\ufff7\015\ufff7\017\ufff7\022\ufff7\001\002\000" +
    "\012\011\ufff6\015\ufff6\017\ufff6\022\ufff6\001\002\000\012" +
    "\011\ufff8\015\ufff8\017\ufff8\022\ufff8\001\002\000\010\020" +
    "\010\021\031\022\024\001\002\000\010\011\035\012\033" +
    "\016\034\001\002\000\010\020\ufff2\021\ufff2\022\ufff2\001" +
    "\002\000\010\020\ufff5\021\ufff5\022\ufff5\001\002\000\010" +
    "\020\ufff0\021\ufff0\022\ufff0\001\002\000\010\020\ufff3\021" +
    "\ufff3\022\ufff3\001\002\000\012\005\ufffd\020\ufffd\021\ufffd" +
    "\022\ufffd\001\002\000\010\020\ufff1\021\ufff1\022\ufff1\001" +
    "\002\000\004\022\051\001\002\000\010\017\uffe4\022\041" +
    "\023\040\001\002\000\004\023\036\001\002\000\004\014" +
    "\037\001\002\000\010\020\uffef\021\uffef\022\uffef\001\002" +
    "\000\006\015\uffe0\017\uffe0\001\002\000\006\015\uffe1\017" +
    "\uffe1\001\002\000\006\015\047\017\uffe5\001\002\000\004" +
    "\017\045\001\002\000\006\015\uffe2\017\uffe2\001\002\000" +
    "\004\014\046\001\002\000\010\020\uffe6\021\uffe6\022\uffe6" +
    "\001\002\000\006\022\041\023\040\001\002\000\006\015" +
    "\uffe3\017\uffe3\001\002\000\004\013\052\001\002\000\004" +
    "\023\053\001\002\000\004\014\054\001\002\000\010\020" +
    "\uffee\021\uffee\022\uffee\001\002\000\006\014\056\016\057" +
    "\001\002\000\016\006\ufffa\007\ufffa\010\ufffa\020\ufffa\021" +
    "\ufffa\022\ufffa\001\002\000\006\017\uffeb\022\060\001\002" +
    "\000\004\013\070\001\002\000\006\015\066\017\uffec\001" +
    "\002\000\004\017\064\001\002\000\006\015\uffe9\017\uffe9" +
    "\001\002\000\004\014\065\001\002\000\016\006\uffed\007" +
    "\uffed\010\uffed\020\uffed\021\uffed\022\uffed\001\002\000\004" +
    "\022\060\001\002\000\006\015\uffea\017\uffea\001\002\000" +
    "\010\006\022\007\020\010\021\001\002\000\010\011\072" +
    "\015\uffe8\017\uffe8\001\002\000\004\023\073\001\002\000" +
    "\006\015\uffe7\017\uffe7\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\072\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\024\006\001\001\000\004\004\010" +
    "\001\001\000\004\025\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\013\001\001\000\012\006\014" +
    "\007\022\013\016\015\015\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\026\010\025\011" +
    "\027\012\024\014\031\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\021\041\022\042\023\043\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\023\047\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\016\060\017\061\020" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\020\066\001\001\000\002\001\001\000\004" +
    "\015\070\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private final Deque<Map<String, SymInfo>> scopes = new ArrayDeque<>();
    private int semanticErrors = 0;

    void openScope() { scopes.push(new HashMap<>()); }
    void closeScope() { scopes.pop(); }

    void sem_error(String msg, int line) {
        semanticErrors++;
        System.out.println("Semanticka greska u liniji " + (line + 1) + ": " + msg);
    }

    SymInfo lookupSym(String name) {
        for (Map<String, SymInfo> s : scopes) {
            SymInfo v = s.get(name);
            if (v != null) return v;
        }
        return null;
    }

    VarInfo lookupVar(String name) {
        SymInfo s = lookupSym(name);
        return (s != null && s.kind == SymKind.VAR) ? s.var : null;
    }

    FuncInfo lookupFunc(String name) {
        SymInfo s = lookupSym(name);
        return (s != null && s.kind == SymKind.FUNC) ? s.func : null;
    }

    void declareVar(String name, MyType t, int line) {
        Map<String, SymInfo> cur = scopes.peek();
        if (cur.containsKey(name)) {
            sem_error("Ime '" + name + "' je vec deklarisano u ovom opsegu.", line);
            return;
        }
        cur.put(name, SymInfo.var(new VarInfo(t, false)));
    }

    void declareFunc(String name, MyType ret, List<ParamInfo> params, int line) {
        Map<String, SymInfo> cur = scopes.peek();
        if (cur.containsKey(name)) {
            sem_error("Ime '" + name + "' je vec deklarisano u ovom opsegu.", line);
            return;
        }
        int min = 0;
        for (ParamInfo p : params) {
            if (!p.hasDefault) min++;
        }
        cur.put(name, SymInfo.func(new FuncInfo(ret, params, min)));
    }

    boolean canImplicitlyConvert(MyType from, MyType to) {
        if (from == null || to == null) return false;
        if (from == to) return true;
        if (from == MyType.CHAR && (to == MyType.INT || to == MyType.FLOAT)) return true;
        if (from == MyType.INT  &&  to == MyType.FLOAT) return true;
        return false;
    }

    MyType constType(String lexeme) {
        if (lexeme == null) return null;
        lexeme = lexeme.trim();
        if (lexeme.matches("'([^'\\\\]|\\\\.)'")) return MyType.CHAR;
        if (lexeme.matches("([0-9]+\\.[0-9]*|\\.[0-9]+)([eE][+-]?[0-9]+)?")) return MyType.FLOAT;
        if (lexeme.matches("0x[0-9a-fA-F]+")) return MyType.INT;
        if (lexeme.matches("0[0-7]+")) return MyType.INT;
        if (lexeme.matches("0|[1-9][0-9]*")) return MyType.INT;
        return null;
    }

    public void report_error(String message, Object info) {
        System.out.print(message);
    }

    public void syntax_error(Symbol cur_token) {
        report_error("Sintaksna greska u liniji " + (cur_token.left + 1) + ": ", cur_token);
        System.out.println("Token '" + cur_token.value + "' nije ocekivan.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Arg ::= CONST 
            {
              MyType RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
       String cval = (String)c;
       int line = cleft;
       MyType ct = parser.constType(cval);
       if (ct == null) {
           parser.sem_error("Nepoznat tip konstante '" + cval + "'.", line);
       }
       RESULT = ct;
     
              CUP$parser$result = new java_cup.runtime.Symbol(17/*Arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Arg ::= ID 
            {
              MyType RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
       String name = (String)i;
       int line = ileft;
       VarInfo v = parser.lookupVar(name);
       if (v == null) {
           parser.sem_error("Promenljiva '" + name + "' nije deklarisana.", line);
           RESULT = null;
       } else {
           if (!v.initialized) {
               parser.sem_error("Promenljiva '" + name + "' nije inicijalizovana.", line);
           }
           RESULT = v.type;
       }
     
              CUP$parser$result = new java_cup.runtime.Symbol(17/*Arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ArgList ::= Arg 
            {
              java.util.List RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		MyType a = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
           List l = new ArrayList();
           l.add(a);
           RESULT = l;
         
              CUP$parser$result = new java_cup.runtime.Symbol(15/*ArgList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ArgList ::= ArgList COMMA Arg 
            {
              java.util.List RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		MyType a = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
           l.add(a);
           RESULT = l;
         
              CUP$parser$result = new java_cup.runtime.Symbol(15/*ArgList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ArgListOpt ::= 
            {
              java.util.List RESULT = null;
		 RESULT = new ArrayList(); 
              CUP$parser$result = new java_cup.runtime.Symbol(16/*ArgListOpt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ArgListOpt ::= ArgList 
            {
              java.util.List RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
               RESULT = l;
             
              CUP$parser$result = new java_cup.runtime.Symbol(16/*ArgListOpt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // FunctionCall ::= ID LPAREN ArgListOpt RPAREN SEMICOLON 
            {
              Object RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List args = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                 String name = (String)i;
                 int line = ileft;
                 List argsList = (List)args;

                 FuncInfo f = parser.lookupFunc(name);
                 if (f == null) {
                     parser.sem_error("Funkcija '" + name + "' nije deklarisana.", line);
                 } else {
                     int argCount = argsList.size();
                     if (argCount < f.minArgs || argCount > f.params.size()) {
                         parser.sem_error("Pogresan broj argumenata za funkciju '" + name + "'.", line);
                     } else {
                         for (int idx = 0; idx < argCount; idx++) {
                             MyType at = (MyType)argsList.get(idx);
                             MyType pt = f.params.get(idx).type;
                             if (at != null && !parser.canImplicitlyConvert(at, pt)) {
                                 parser.sem_error("Argument #" + (idx + 1) + " nije kompatibilan sa tipom " + pt + ".", line);
                             }
                         }
                     }
                 }
               
              CUP$parser$result = new java_cup.runtime.Symbol(10/*FunctionCall*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Param ::= ID COLON T ASSIGN CONST 
            {
              ParamInfo RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyType t = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
          String name = (String)i;
          int line = ileft;
          MyType ptype = (MyType)t;
          String cval = (String)c;
          MyType ct = parser.constType(cval);
          if (ct == null) {
              parser.sem_error("Nepoznat tip konstante '" + cval + "'.", cleft);
          } else if (ct != ptype) {
              parser.sem_error("Podrazumevana vrednost parametra '" + name + "' nije tipa " + ptype + ".", line);
          }
          RESULT = new ParamInfo(name, ptype, true);
        
              CUP$parser$result = new java_cup.runtime.Symbol(14/*Param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Param ::= ID COLON T 
            {
              ParamInfo RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		MyType t = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
          String name = (String)i;
          MyType ptype = (MyType)t;
          RESULT = new ParamInfo(name, ptype, false);
        
              CUP$parser$result = new java_cup.runtime.Symbol(14/*Param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ParamList ::= Param 
            {
              java.util.List RESULT = null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		ParamInfo p = (ParamInfo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
              List l = new ArrayList();
              l.add(p);
              RESULT = l;
            
              CUP$parser$result = new java_cup.runtime.Symbol(12/*ParamList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ParamList ::= ParamList COMMA Param 
            {
              java.util.List RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		ParamInfo p = (ParamInfo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
              l.add(p);
              RESULT = l;
            
              CUP$parser$result = new java_cup.runtime.Symbol(12/*ParamList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ParamListOpt ::= 
            {
              java.util.List RESULT = null;
		 RESULT = new ArrayList(); 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*ParamListOpt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ParamListOpt ::= ParamList 
            {
              java.util.List RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		java.util.List l = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
                 RESULT = l;
               
              CUP$parser$result = new java_cup.runtime.Symbol(13/*ParamListOpt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // FunctionDecl ::= T ID LPAREN ParamListOpt RPAREN SEMICOLON 
            {
              Object RESULT = null;
		int rtleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int rtright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		MyType rt = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List params = (java.util.List)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                 MyType rtype = (MyType)rt;
                 String name = (String)i;
                 int line = ileft;
                 List paramsList = (List)params;

                 HashSet<String> seen = new HashSet<>();
                 for (Object o : paramsList) {
                     ParamInfo p = (ParamInfo)o;
                     if (seen.contains(p.name)) {
                         parser.sem_error("Parametar '" + p.name + "' je vec deklarisan u ovoj funkciji.", line);
                     } else {
                         seen.add(p.name);
                     }
                 }

                 parser.declareFunc(name, rtype, paramsList, line);
               
              CUP$parser$result = new java_cup.runtime.Symbol(9/*FunctionDecl*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Mapping ::= ID ARROW ID COLON CONST SEMICOLON 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            String leftId = (String)l;
            int leftLine = lleft;

            String rightId = (String)r;
            int rightLine = rleft;

            String cval = (String)c;
            int cLine = cleft;

            VarInfo L = parser.lookupVar(leftId);
            if (L == null) parser.sem_error("ID '" + leftId + "' nije deklarisan.", leftLine);

            VarInfo R = parser.lookupVar(rightId);
            if (R == null) parser.sem_error("ID '" + rightId + "' nije deklarisan.", rightLine);

            if (R != null && !R.initialized) {
                parser.sem_error("Promenljiva '" + rightId + "' nije inicijalizovana.", rightLine);
            }

            MyType ct = parser.constType(cval);
            if (ct == null) {
                parser.sem_error("Nepoznat tip konstante '" + cval + "'.", cLine);
            } else if (L != null && !parser.canImplicitlyConvert(ct, L.type)) {
                parser.sem_error("Konstanta tipa " + ct + " nije kompatibilna sa '" + leftId +
                          "' tipa " + L.type + ".", leftLine);
            } else if (L != null) {
                L.initialized = true;
            }
          
              CUP$parser$result = new java_cup.runtime.Symbol(8/*Mapping*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Assignment ::= ID ASSIGN CONST SEMICOLON 
            {
              Object RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                String id = (String)i;
                int idLine = ileft;

                String cval = (String)c;
                int cLine = cleft;

                VarInfo v = parser.lookupVar(id);
                if (v == null) {
                    parser.sem_error("Promenljiva '" + id + "' nije deklarisana.", idLine);
                } else {
                    MyType ct = parser.constType(cval);
                    if (ct == null) {
                        parser.sem_error("Nepoznat tip konstante '" + cval + "'.", cLine);
                    } else if (!parser.canImplicitlyConvert(ct, v.type)) {
                        parser.sem_error("Ne moze dodela tipa " + ct + " u '" + id + "' tipa " + v.type + ".", idLine);
                    } else {
                        v.initialized = true;
                    }
                }
              
              CUP$parser$result = new java_cup.runtime.Symbol(7/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Statement ::= Block 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statement ::= FunctionCall 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statement ::= Mapping 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statement ::= Assignment 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // StatementList ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*StatementList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*StatementList*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // T ::= CHAR 
            {
              MyType RESULT = null;
		 RESULT = MyType.CHAR;  
              CUP$parser$result = new java_cup.runtime.Symbol(11/*T*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // T ::= FLOAT 
            {
              MyType RESULT = null;
		 RESULT = MyType.FLOAT; 
              CUP$parser$result = new java_cup.runtime.Symbol(11/*T*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // T ::= INT 
            {
              MyType RESULT = null;
		 RESULT = MyType.INT;   
              CUP$parser$result = new java_cup.runtime.Symbol(11/*T*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Declaration ::= FunctionDecl 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declaration ::= T ID SEMICOLON 
            {
              Object RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyType t = (MyType)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                String name = (String)i;
                int line = ileft;
                MyType ttype = (MyType)t;
                parser.declareVar(name, ttype, line);
              
              CUP$parser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Declarations ::= 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declarations ::= Declarations Declaration 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Block ::= LBRACE NT$1 Declarations StatementList RBRACE 
            {
              Object RESULT = null;
              // propagate RESULT from NT$1
              if ( ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 parser.closeScope(); 
              CUP$parser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$1 ::= 
            {
              Object RESULT = null;
 parser.openScope(); 
              CUP$parser$result = new java_cup.runtime.Symbol(19/*NT$1*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= PROGRAM ID NT$0 Block END 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 parser.closeScope(); 
              CUP$parser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT = null;
 parser.openScope(); 
              CUP$parser$result = new java_cup.runtime.Symbol(18/*NT$0*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

