
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 25 18:24:22 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 10;
  public static final int RBRACE = 15;
  public static final int RPAREN = 13;
  public static final int INT = 4;
  public static final int CHAR = 6;
  public static final int END = 3;
  public static final int LPAREN = 12;
  public static final int COLON = 9;
  public static final int LBRACE = 14;
  public static final int ID = 16;
  public static final int PROGRAM = 2;
  public static final int COMMA = 11;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int CONST = 17;
  public static final int error = 1;
  public static final int ARROW = 8;
  public static final int ASSIGN = 7;
}

