
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 06 13:53:26 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.lang.reflect.Field;

/** CUP v0.10k generated parser.
  * @version Tue Jan 06 13:53:26 CET 2026
  */
public class parser_err extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser_err() {super();}

  /** Constructor which sets the default scanner. */
  public parser_err(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\023\000\002\002\004\000\002\003\006\000\002\003" +
    "\005\000\002\004\006\000\002\005\004\000\002\005\002" +
    "\000\002\006\005\000\002\006\005\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\010\004\000\002" +
    "\010\002\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\004\000\002\012\006\000\002\013\010" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\045\000\004\004\005\001\002\000\004\002\047\001" +
    "\002\000\006\003\007\022\006\001\002\000\004\020\011" +
    "\001\002\000\004\005\010\001\002\000\004\002\uffff\001" +
    "\002\000\020\003\ufffc\006\ufffc\007\ufffc\010\ufffc\020\ufffc" +
    "\021\ufffc\022\ufffc\001\002\000\004\005\013\001\002\000" +
    "\004\002\000\001\002\000\020\003\ufff5\006\021\007\017" +
    "\010\020\020\ufff5\021\ufff5\022\ufff5\001\002\000\020\003" +
    "\ufffd\006\ufffd\007\ufffd\010\ufffd\020\ufffd\021\ufffd\022\ufffd" +
    "\001\002\000\006\003\044\022\043\001\002\000\006\003" +
    "\ufff8\022\ufff8\001\002\000\006\003\ufff7\022\ufff7\001\002" +
    "\000\006\003\ufff9\022\ufff9\001\002\000\012\003\025\020" +
    "\011\021\031\022\023\001\002\000\006\011\034\012\033" +
    "\001\002\000\012\003\ufff3\020\ufff3\021\ufff3\022\ufff3\001" +
    "\002\000\004\014\032\001\002\000\012\003\ufff2\020\ufff2" +
    "\021\ufff2\022\ufff2\001\002\000\012\003\ufff6\020\ufff6\021" +
    "\ufff6\022\ufff6\001\002\000\012\003\ufff4\020\ufff4\021\ufff4" +
    "\022\ufff4\001\002\000\014\003\ufffe\005\ufffe\020\ufffe\021" +
    "\ufffe\022\ufffe\001\002\000\012\003\ufff1\020\ufff1\021\ufff1" +
    "\022\ufff1\001\002\000\004\022\037\001\002\000\004\023" +
    "\035\001\002\000\004\014\036\001\002\000\012\003\ufff0" +
    "\020\ufff0\021\ufff0\022\ufff0\001\002\000\004\013\040\001" +
    "\002\000\004\023\041\001\002\000\004\014\042\001\002" +
    "\000\012\003\uffef\020\uffef\021\uffef\022\uffef\001\002\000" +
    "\004\014\046\001\002\000\004\014\045\001\002\000\020" +
    "\003\ufffa\006\ufffa\007\ufffa\010\ufffa\020\ufffa\021\ufffa\022" +
    "\ufffa\001\002\000\020\003\ufffb\006\ufffb\007\ufffb\010\ufffb" +
    "\020\ufffb\021\ufffb\022\ufffb\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\045\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\006\014\007\015\010\021" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\004\025" +
    "\011\026\012\027\013\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser_err$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser_err$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser_err$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Metoda koja mapira imena konstanti u prave simbole
    public String getTokenName(int id) {
        String name = "UNKNOWN";
        try {
            java.lang.reflect.Field[] fields = sym.class.getFields();
            for (java.lang.reflect.Field f : fields) {
                if (f.getInt(null) == id) {
                    name = f.getName();
                    break;
                }
            }
        } catch (Exception e) {
            return String.valueOf(id);
        }

        // DODATO: Mapiranje imena u simbole radi lepseg ispisa
        if (name.equals("SEMICOLON")) return "';'";
        if (name.equals("COMMA"))     return "','";
        if (name.equals("ASSIGN"))    return "'='";
        if (name.equals("COLON"))     return "':'";
        if (name.equals("LPAREN"))    return "'('";
        if (name.equals("RPAREN"))    return "')'";
        if (name.equals("LBRACE"))    return "'{'";
        if (name.equals("RBRACE"))    return "'}'";
        if (name.equals("ARROW"))     return "'=>'";
        if (name.equals("DOT"))       return "'.'";
        
        return name;
    }

    public java.util.List<String> getExpectedTokens() {
        java.util.List<String> tokens = new java.util.ArrayList<String>();
        try {
            int state = ((java_cup.runtime.Symbol)stack.peek()).parse_state;
            short[] row = action_table()[state];
            for (int i = 0; i < row.length; i += 2) {
                int termId = row[i];
                if (termId != -1) {
                    String name = getTokenName(termId);
                    if (!tokens.contains(name) && !name.equals("error") && !name.equals("EOF")) {
                        tokens.add(name);
                    }
                }
            }
        } catch (Exception e) {}
        return tokens;
    }

    public void syntax_error(java_cup.runtime.Symbol cur_token) {
        String imeTokena = getTokenName(cur_token.sym);
        String vrednost = (cur_token.value != null) ? cur_token.value.toString() : "null";
        java.util.List<String> ocekivani = getExpectedTokens();
        
        System.err.println("\n[SINTAKSNA GRESKA]");
        System.err.println("----------------------------------------------");
        System.err.println("Greska na liniji: " + (cur_token.left + 1));
        System.err.println("Neocekivan token: " + vrednost + " (" + imeTokena + ")");
        
        if (ocekivani != null && !ocekivani.isEmpty()) {
            System.err.print("Ocekivano je jedno od: ");
            for (int i = 0; i < ocekivani.size(); i++) {
                System.err.print(ocekivani.get(i));
                if (i < ocekivani.size() - 1) System.err.print(", ");
            }
            System.err.println();
        }
        System.err.println("----------------------------------------------");
    }

    public void unrecovered_syntax_error(java_cup.runtime.Symbol cur_token) throws java.lang.Exception {
        System.err.println("FATALNA GRESKA: Analiza prekinuta.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser_err$actions {
  private final parser_err parser;

  /** Constructor */
  CUP$parser_err$actions(parser_err parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser_err$do_action(
    int                        CUP$parser_err$act_num,
    java_cup.runtime.lr_parser CUP$parser_err$parser,
    java.util.Stack            CUP$parser_err$stack,
    int                        CUP$parser_err$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser_err$result;

      /* select the action based on the action number */
      switch (CUP$parser_err$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Mapping ::= ID ARROW ID COLON CONST SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*Mapping*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Assignment ::= ID ASSIGN CONST SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statement ::= error SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Greska u naredbi. Preskacem do ';'."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statement ::= Block 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statement ::= Mapping 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Statement ::= Assignment 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // StatementList ::= 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*StatementList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*StatementList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= CHAR 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= FLOAT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declaration ::= Type error SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Greska u deklaraciji promenljive."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Declaration ::= Type ID SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declarations ::= 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Declarations ::= Declarations Declaration 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Block ::= LBRACE Declarations StatementList RBRACE 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= PROGRAM error END 
            {
              Object RESULT = null;
		 System.out.println("Greska u strukturi programa."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= PROGRAM ID Block END 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).value;
		RESULT = start_val;
              CUP$parser_err$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser_err$parser.done_parsing();
          return CUP$parser_err$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

