
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 12 16:18:56 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Mon Jan 12 16:18:56 CET 2026
  */
public class parser_err extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser_err() {super();}

  /** Constructor which sets the default scanner. */
  public parser_err(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\046\000\002\002\004\000\002\003\006\000\002\003" +
    "\005\000\002\004\006\000\002\005\004\000\002\005\003" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\010\005\000\002\010\003\000\002\011\003\000\002\011" +
    "\003\000\002\012\011\000\002\012\007\000\002\013\004" +
    "\000\002\013\003\000\002\013\003\000\002\013\002\000" +
    "\002\014\004\000\002\014\003\000\002\015\010\000\002" +
    "\016\005\000\002\017\005\000\002\017\003\000\002\020" +
    "\003\000\002\020\003\000\002\021\003\000\002\021\003" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\022\005\000\002\022\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\004\004\005\001\002\000\004\002\111\001" +
    "\002\000\006\003\006\005\007\001\002\000\004\007\012" +
    "\001\002\000\004\006\010\001\002\000\004\007\012\001" +
    "\002\000\004\002\000\001\002\000\012\003\014\014\020" +
    "\015\015\016\017\001\002\000\006\003\105\030\104\001" +
    "\002\000\004\030\102\001\002\000\006\003\ufff7\030\ufff7" +
    "\001\002\000\016\003\ufffc\014\ufffc\015\ufffc\016\ufffc\017" +
    "\ufffc\030\ufffc\001\002\000\006\003\ufff6\030\ufff6\001\002" +
    "\000\006\003\ufff8\030\ufff8\001\002\000\016\003\014\014" +
    "\020\015\015\016\017\017\026\030\030\001\002\000\006" +
    "\010\ufff3\011\ufff3\001\002\000\016\003\ufffd\014\ufffd\015" +
    "\ufffd\016\ufffd\017\ufffd\030\ufffd\001\002\000\006\010\100" +
    "\011\077\001\002\000\006\010\ufff2\011\ufff2\001\002\000" +
    "\006\003\036\005\037\001\002\000\006\010\ufff4\011\ufff4" +
    "\001\002\000\004\013\031\001\002\000\010\003\035\030" +
    "\032\031\033\001\002\000\024\006\uffe5\010\uffe5\011\uffe5" +
    "\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5\001" +
    "\002\000\024\006\uffe4\010\uffe4\011\uffe4\022\uffe4\023\uffe4" +
    "\024\uffe4\025\uffe4\026\uffe4\027\uffe4\001\002\000\006\010" +
    "\uffdd\011\uffdd\001\002\000\006\010\uffdc\011\uffdc\001\002" +
    "\000\004\012\074\001\002\000\006\030\032\031\033\001" +
    "\002\000\004\006\052\001\002\000\020\006\uffe6\022\047" +
    "\023\045\024\044\025\050\026\046\027\043\001\002\000" +
    "\006\030\032\031\033\001\002\000\006\030\uffde\031\uffde" +
    "\001\002\000\006\030\uffe1\031\uffe1\001\002\000\006\030" +
    "\uffe2\031\uffe2\001\002\000\006\030\uffdf\031\uffdf\001\002" +
    "\000\006\030\uffe3\031\uffe3\001\002\000\006\030\uffe0\031" +
    "\uffe0\001\002\000\004\006\uffe7\001\002\000\004\012\053" +
    "\001\002\000\004\007\012\001\002\000\012\010\uffec\011" +
    "\uffec\020\056\021\060\001\002\000\012\010\uffee\011\uffee" +
    "\020\056\021\060\001\002\000\004\012\070\001\002\000" +
    "\006\010\ufff1\011\ufff1\001\002\000\004\005\063\001\002" +
    "\000\006\010\uffed\011\uffed\001\002\000\012\010\uffea\011" +
    "\uffea\020\uffea\021\uffea\001\002\000\006\030\032\031\033" +
    "\001\002\000\004\006\065\001\002\000\004\012\066\001" +
    "\002\000\004\007\012\001\002\000\012\010\uffe9\011\uffe9" +
    "\020\uffe9\021\uffe9\001\002\000\004\007\012\001\002\000" +
    "\006\010\uffe8\011\uffe8\001\002\000\006\010\uffef\011\uffef" +
    "\001\002\000\012\010\uffeb\011\uffeb\020\uffeb\021\uffeb\001" +
    "\002\000\004\007\012\001\002\000\012\010\uffec\011\uffec" +
    "\020\056\021\060\001\002\000\006\010\ufff0\011\ufff0\001" +
    "\002\000\006\017\026\030\030\001\002\000\014\002\ufffe" +
    "\010\ufffe\011\ufffe\020\ufffe\021\ufffe\001\002\000\006\010" +
    "\ufff5\011\ufff5\001\002\000\004\011\103\001\002\000\016" +
    "\003\ufff9\014\ufff9\015\ufff9\016\ufff9\017\ufff9\030\ufff9\001" +
    "\002\000\004\011\107\001\002\000\004\011\106\001\002" +
    "\000\016\003\ufffa\014\ufffa\015\ufffa\016\ufffa\017\ufffa\030" +
    "\ufffa\001\002\000\016\003\ufffb\014\ufffb\015\ufffb\016\ufffb" +
    "\017\ufffb\030\ufffb\001\002\000\004\002\uffff\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\107\001\001\000\002\001\001" +
    "\000\004\004\010\001\001\000\002\001\001\000\010\005" +
    "\020\006\015\007\012\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\006\022\007\012\010\023" +
    "\011\026\012\024\022\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\020" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\017" +
    "\037\020\040\001\001\000\002\001\001\000\004\021\041" +
    "\001\001\000\004\020\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\053\001\001\000\012\013\056\014\054" +
    "\015\061\016\060\001\001\000\006\015\072\016\071\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\017\063\020" +
    "\040\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\066\001\001\000\002\001\001\000\004\004\070\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\074\001\001\000\012\013\075\014\054\015" +
    "\061\016\060\001\001\000\002\001\001\000\010\011\100" +
    "\012\024\022\021\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser_err$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser_err$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser_err$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        System.err.println("Sintaksna greska: Linija " + (cur_token.left + 1) + ", Kolona " + (cur_token.right + 1));
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser_err$actions {
  private final parser_err parser;

  /** Constructor */
  CUP$parser_err$actions(parser_err parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser_err$do_action(
    int                        CUP$parser_err$act_num,
    java_cup.runtime.lr_parser CUP$parser_err$parser,
    java.util.Stack            CUP$parser_err$stack,
    int                        CUP$parser_err$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser_err$result;

      /* select the action based on the action number */
      switch (CUP$parser_err$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Assignment ::= ID ASSIGN error 
            {
              Object RESULT = null;
		 System.out.println("Oporavak: Los izraz u dodeli vrednosti."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(16/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Assignment ::= ID ASSIGN Term 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(16/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // RelOp ::= GREATEREQ 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // RelOp ::= GREATER 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // RelOp ::= NEQ 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // RelOp ::= EQ 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // RelOp ::= LESSEQ 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RelOp ::= LESS 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Term ::= CONST 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(14/*Term*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Term ::= ID 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(14/*Term*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // RelExpression ::= Term 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(13/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(13/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ElseStatement ::= ELSE COLON Block 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(12/*ElseStatement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Elif ::= ELIF LEFTPAR RelExpression RIGHTPAR COLON Block 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(11/*Elif*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ElifList ::= Elif 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(10/*ElifList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ElifList ::= ElifList Elif 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(10/*ElifList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ElsePart ::= 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ElsePart ::= ElseStatement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ElsePart ::= ElifList 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ElsePart ::= ElifList ElseStatement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // IfStatement ::= IF error COLON Block ElsePart 
            {
              Object RESULT = null;
		 System.out.println("Oporavak: Greska u uslovu IF naredbe."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(8/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // IfStatement ::= IF LEFTPAR RelExpression RIGHTPAR COLON Block ElsePart 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(8/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statement ::= IfStatement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Statement ::= Assignment 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Statements ::= Statement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*Statements*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Statements ::= Statements SEMICOLON Statement 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*Statements*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Type ::= BOOLEAN 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= REAL 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Variable ::= error ID SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Oporavak: Los tip u deklaraciji promenljive."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Variable*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Variable ::= Type error SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Oporavak: Los ID u deklaraciji promenljive."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Variable*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Variable ::= Type ID SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Variable*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Variables ::= Variable 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Variables ::= Variables Variable 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Block ::= BLOCK_BEGIN Variables Statements BLOCK_END 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= MAIN error Block 
            {
              Object RESULT = null;
		 System.out.println("Oporavak: Greska u zaglavlju main funkcije."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= MAIN LEFTPAR RIGHTPAR Block 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).value;
		RESULT = start_val;
              CUP$parser_err$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser_err$parser.done_parsing();
          return CUP$parser_err$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

