
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 12 16:18:56 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 7;
  public static final int ELSE = 14;
  public static final int INT = 10;
  public static final int LEFTPAR = 3;
  public static final int GREATER = 20;
  public static final int BLOCK_END = 6;
  public static final int RIGHTPAR = 4;
  public static final int IF = 13;
  public static final int COLON = 8;
  public static final int ID = 22;
  public static final int BOOLEAN = 12;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int GREATEREQ = 21;
  public static final int ELIF = 15;
  public static final int CONST = 23;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int LESSEQ = 17;
  public static final int ASSIGN = 9;
  public static final int BLOCK_BEGIN = 5;
  public static final int REAL = 11;
  public static final int NEQ = 19;
  public static final int LESS = 16;
}

