
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 05 22:23:55 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Mon Jan 05 22:23:55 CET 2026
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\003\005\000\002\002\004\000\002\003" +
    "\005\000\002\003\004\000\002\003\003\000\002\004\006" +
    "\000\002\004\006\000\002\004\004\000\002\005\004\000" +
    "\002\005\002\000\002\006\006\000\002\006\006\000\002" +
    "\006\005\000\002\007\005\000\002\007\005\000\002\007" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\011\004\000\002\011\003\000" +
    "\002\012\003\000\002\012\006\000\002\012\006\000\002" +
    "\012\005\000\002\012\003\000\002\013\006\000\002\013" +
    "\006\000\002\013\004\000\002\014\004\000\002\014\003" +
    "\000\002\015\006\000\002\015\006\000\002\015\004\000" +
    "\002\016\005\000\002\016\003\000\002\017\005\000\002" +
    "\017\003\000\002\020\005\000\002\020\003\000\002\021" +
    "\003\000\002\021\003\000\002\021\003\000\002\021\003" +
    "\000\002\021\003\000\002\021\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\005\000\002\022\005\000\002" +
    "\022\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\006\003\005\004\006\001\002\000\004\002" +
    "\116\001\002\000\004\002\ufffd\001\002\000\006\003\007" +
    "\005\011\001\002\000\004\002\ufffe\001\002\000\006\003" +
    "\114\035\115\001\002\000\012\003\012\005\ufff8\013\ufff8" +
    "\017\ufff8\001\002\000\020\003\ufffa\005\ufffa\006\ufffa\013" +
    "\ufffa\014\ufffa\017\ufffa\035\ufffa\001\002\000\010\005\011" +
    "\013\023\017\022\001\002\000\006\034\100\036\101\001" +
    "\002\000\016\003\uffe7\005\uffe7\006\uffe7\013\uffe7\014\uffe7" +
    "\017\uffe7\001\002\000\016\003\uffeb\005\uffeb\006\uffeb\013" +
    "\uffeb\014\uffeb\017\uffeb\001\002\000\014\003\075\005\011" +
    "\006\077\013\023\017\055\001\002\000\010\005\ufff9\013" +
    "\ufff9\017\ufff9\001\002\000\014\003\uffec\005\uffec\006\uffec" +
    "\013\uffec\017\uffec\001\002\000\010\021\060\034\ufff2\036" +
    "\ufff2\001\002\000\006\003\024\005\025\001\002\000\016" +
    "\003\uffe4\005\uffe4\006\uffe4\013\uffe4\014\uffe4\017\uffe4\001" +
    "\002\000\004\014\027\001\002\000\010\003\uffe2\006\uffe2" +
    "\014\uffe2\001\002\000\012\003\040\017\035\020\036\031" +
    "\043\001\002\000\010\003\032\006\033\014\027\001\002" +
    "\000\010\003\uffe3\006\uffe3\014\uffe3\001\002\000\016\003" +
    "\uffe5\005\uffe5\006\uffe5\013\uffe5\014\uffe5\017\uffe5\001\002" +
    "\000\016\003\uffe6\005\uffe6\006\uffe6\013\uffe6\014\uffe6\017" +
    "\uffe6\001\002\000\016\003\uffdb\015\uffdb\016\uffdb\022\uffdb" +
    "\032\uffdb\033\uffdb\001\002\000\032\003\uffd2\015\uffd2\016" +
    "\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\026\uffd2\027\uffd2" +
    "\030\uffd2\032\uffd2\033\uffd2\001\002\000\032\003\uffd1\015" +
    "\uffd1\016\uffd1\022\uffd1\023\uffd1\024\uffd1\025\uffd1\026\uffd1" +
    "\027\uffd1\030\uffd1\032\uffd1\033\uffd1\001\002\000\032\003" +
    "\uffd9\015\uffd9\016\uffd9\022\uffd9\023\067\024\071\025\066" +
    "\026\073\027\070\030\072\032\uffd9\033\uffd9\001\002\000" +
    "\010\003\uffdf\006\uffdf\014\uffdf\001\002\000\006\015\050" +
    "\022\054\001\002\000\016\003\uffdd\015\uffdd\016\052\022" +
    "\uffdd\032\uffdd\033\uffdd\001\002\000\012\003\044\017\035" +
    "\020\036\031\043\001\002\000\032\003\uffce\015\uffce\016" +
    "\uffce\022\uffce\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce" +
    "\030\uffce\032\uffce\033\uffce\001\002\000\010\003\047\015" +
    "\050\032\046\001\002\000\032\003\uffd0\015\uffd0\016\uffd0" +
    "\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0\027\uffd0\030" +
    "\uffd0\032\uffd0\033\uffd0\001\002\000\032\003\uffcf\015\uffcf" +
    "\016\uffcf\022\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027" +
    "\uffcf\030\uffcf\032\uffcf\033\uffcf\001\002\000\010\017\035" +
    "\020\036\031\043\001\002\000\016\003\uffde\015\uffde\016" +
    "\052\022\uffde\032\uffde\033\uffde\001\002\000\010\017\035" +
    "\020\036\031\043\001\002\000\016\003\uffdc\015\uffdc\016" +
    "\uffdc\022\uffdc\032\uffdc\033\uffdc\001\002\000\012\003\056" +
    "\005\011\013\023\017\055\001\002\000\004\021\060\001" +
    "\002\000\010\003\uffe0\006\uffe0\014\uffe0\001\002\000\010" +
    "\003\uffe1\006\uffe1\014\uffe1\001\002\000\012\003\061\017" +
    "\035\020\036\031\043\001\002\000\016\003\uffe8\005\uffe8" +
    "\006\uffe8\013\uffe8\014\uffe8\017\uffe8\001\002\000\010\003" +
    "\064\015\050\033\063\001\002\000\016\003\uffea\005\uffea" +
    "\006\uffea\013\uffea\014\uffea\017\uffea\001\002\000\016\003" +
    "\uffe9\005\uffe9\006\uffe9\013\uffe9\014\uffe9\017\uffe9\001\002" +
    "\000\010\017\035\020\036\031\043\001\002\000\010\017" +
    "\uffd6\020\uffd6\031\uffd6\001\002\000\010\017\uffd8\020\uffd8" +
    "\031\uffd8\001\002\000\010\017\uffd4\020\uffd4\031\uffd4\001" +
    "\002\000\010\017\uffd7\020\uffd7\031\uffd7\001\002\000\010" +
    "\017\uffd3\020\uffd3\031\uffd3\001\002\000\010\017\uffd5\020" +
    "\uffd5\031\uffd5\001\002\000\016\003\uffda\015\uffda\016\uffda" +
    "\022\uffda\032\uffda\033\uffda\001\002\000\020\003\ufffb\005" +
    "\ufffb\006\ufffb\013\ufffb\014\ufffb\017\ufffb\035\ufffb\001\002" +
    "\000\014\003\uffed\005\uffed\006\uffed\013\uffed\017\uffed\001" +
    "\002\000\020\003\ufffc\005\ufffc\006\ufffc\013\ufffc\014\ufffc" +
    "\017\ufffc\035\ufffc\001\002\000\006\003\113\017\112\001" +
    "\002\000\014\003\104\007\102\010\106\011\105\012\107" +
    "\001\002\000\006\003\ufff1\033\ufff1\001\002\000\006\003" +
    "\111\033\110\001\002\000\010\005\ufff5\013\ufff5\017\ufff5" +
    "\001\002\000\006\003\uffef\033\uffef\001\002\000\006\003" +
    "\ufff0\033\ufff0\001\002\000\006\003\uffee\033\uffee\001\002" +
    "\000\010\005\ufff7\013\ufff7\017\ufff7\001\002\000\010\005" +
    "\ufff6\013\ufff6\017\ufff6\001\002\000\006\034\ufff4\036\ufff4" +
    "\001\002\000\006\034\ufff3\036\ufff3\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\001\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\114\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\012\001\001\000\002\001" +
    "\001\000\016\004\014\006\017\007\013\011\016\012\020" +
    "\013\015\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\004\014\012\075\013\015\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\014\027\015\025" +
    "\001\001\000\002\001\001\000\012\016\040\017\041\020" +
    "\033\022\036\001\001\000\004\015\030\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\064" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\016\044\017\041\020\033\022\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\017\050\020\033\022\036\001\001" +
    "\000\002\001\001\000\006\020\052\022\036\001\001\000" +
    "\002\001\001\000\010\004\014\012\056\013\015\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\016\061\017\041\020\033\022\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\073\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\102\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




   public int errNo = 0;
   
   public static void main( String[] args )
   {
      try {
           FileReader file = new FileReader(args[0]);
           Scanner scanner = new MPLexer(file);
           MPParser parser = new MPParser(scanner);
           parser.parse();
           if (parser.errNo == 0)
              System.out.println("Analiza zavrsena. U kodu nema gresaka.");
           else
              System.out.println("Analiza zavrsena. Broj gresaka: " + parser.errNo);
      } catch(Exception e) {
           e.printStackTrace();
      }
   }
   
   public void syntax_error(Symbol cur_token) {}
   
   public void report_error(String message, Object info) {
       System.out.print(message);
   }

   public int getLine() {
      return ((MPLexer)getScanner()).getLine();
   }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Term ::= LEFTPAR error 
            {
              Object RESULT = null;
		 
            System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektan izraz u zagradama");
            parser.errNo++;
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Term ::= LEFTPAR Expression error 
            {
              Object RESULT = null;
		 
            System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ')'");
            parser.errNo++;
         
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Term ::= LEFTPAR Expression RIGHTPAR 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 35: Term ::= ( Expression )"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Term ::= CONST 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 34: Term ::= CONST"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Term ::= ID 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 33: Term ::= ID"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // RelOp ::= GE 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 32: RelOp ::= >="); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // RelOp ::= GT 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 31: RelOp ::= >"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // RelOp ::= NE 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 30: RelOp ::= <>"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // RelOp ::= EQ 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 29: RelOp ::= =="); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // RelOp ::= LE 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 28: RelOp ::= <="); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // RelOp ::= LT 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 27: RelOp ::= <"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // RelExpression ::= Term 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 26: RelExpression ::= Term"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 25: RelExpression ::= Term RelOp Term"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // AndExpression ::= RelExpression 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 24: AndExpression ::= RelExpression"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // AndExpression ::= AndExpression AND RelExpression 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 23: AndExpression ::= AndExpression and RelExpression"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Expression ::= AndExpression 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 22: Expression ::= AndExpression"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Expression ::= Expression OR AndExpression 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 21: Expression ::= Expression or AndExpression"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Case ::= CASE error 
            {
              Object RESULT = null;
		 
          System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektan case");
          parser.errNo++;
       
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Case*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Case ::= CASE Expression ARROW error 
            {
              Object RESULT = null;
		 
          System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje naredba u case grani");
          parser.errNo++;
       
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Case*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Case ::= CASE Expression ARROW Statement 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 20: Case ::= case Expression => Statement"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Case*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // CaseList ::= Case 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 19: CaseList ::= Case"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*CaseList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // CaseList ::= CaseList Case 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 18: CaseList ::= CaseList Case"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*CaseList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // SelectStatement ::= SELECT error 
            {
              Object RESULT = null;
		 
                     System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektan select");
                     parser.errNo++;
                  
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*SelectStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // SelectStatement ::= SELECT BEGIN CaseList error 
            {
              Object RESULT = null;
		 
                     System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje 'end' u select naredbi");
                     parser.errNo++;
                  
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*SelectStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // SelectStatement ::= SELECT BEGIN CaseList END 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 17: SelectStatement ::= select begin CaseList end"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*SelectStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Statement ::= Block 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 16: Statement ::= Block"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Statement ::= ID ASSIGN error 
            {
              Object RESULT = null;
		 
               System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektan izraz u dodeli");
               parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Statement ::= ID ASSIGN Expression error 
            {
              Object RESULT = null;
		 
               System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ';' nakon dodele");
               parser.errNo++;
            
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 15: Statement ::= ID := Expression ;"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Statement ::= SelectStatement 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 14: Statement ::= SelectStatement"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // StatementList ::= Statement 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 13: StatementList ::= Statement"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 12: StatementList ::= StatementList Statement"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*StatementList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Type ::= BOOLEAN 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 11: Tip ::= boolean"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= REAL 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 10: Tip ::= real"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= CHAR 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 9: Tip ::= char"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= INTEGER 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 8: Tip ::= integer"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NameList ::= ID 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 7: NameList ::= ID"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NameList ::= NameList COMMA error 
            {
              Object RESULT = null;
		 
              System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje identifikator nakon ','");
              parser.errNo++;
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NameList ::= NameList COMMA ID 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 6: NameList ::= NameList , ID"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*NameList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Declaration ::= NameList COLON error 
            {
              Object RESULT = null;
		 
                 System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektan tip");
                 parser.errNo++;
              
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Declaration ::= NameList COLON Type error 
            {
              Object RESULT = null;
		 
                 System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje ';' u deklaraciji");
                 parser.errNo++;
              
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Declaration ::= NameList COLON Type SEMICOLON 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 5: Declaration ::= NameList : Type ;"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Variables ::= 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 4: Variables ::= epsilon"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Variables ::= Variables Declaration 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 3: Variables ::= Variables Declaration"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Block ::= BEGIN error 
            {
              Object RESULT = null;
		 
           System.out.println("Greska u liniji " + parser.getLine() + ": Nekorektno telo bloka");
           parser.errNo++;
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Block ::= BEGIN Variables StatementList error 
            {
              Object RESULT = null;
		 
           System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje 'end'");
           parser.errNo++;
        
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Block ::= BEGIN Variables StatementList END 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 2: Block ::= begin Variables StatementList end"); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= error 
            {
              Object RESULT = null;
		 
              System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje kljucna rec 'program'");
              parser.errNo++;
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= PROGRAM error 
            {
              Object RESULT = null;
		 
              System.out.println("Greska u liniji " + parser.getLine() + ": Telo programa je nekorektno");
              parser.errNo++;
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= PROGRAM Block error 
            {
              Object RESULT = null;
		 
              System.out.println("Greska u liniji " + parser.getLine() + ": Nedostaje '.' na kraju programa");
              parser.errNo++;
           
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= PROGRAM Block DOT 
            {
              Object RESULT = null;
		 System.out.println("Redukcija 1: Program ::= program Block ."); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

