
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 01 15:57:59 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import AST.*;

/** CUP v0.10k generated parser.
  * @version Sun Feb 01 15:57:59 CET 2026
  */
public class parser_g4 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser_g4() {super();}

  /** Constructor which sets the default scanner. */
  public parser_g4(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\003\010\000\002\004" +
    "\004\000\002\004\002\000\002\005\003\000\002\005\003" +
    "\000\002\006\006\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\007\011\000\002\007\010\000\002" +
    "\011\005\000\002\011\003\000\002\010\005\000\002\012" +
    "\005\000\002\012\003\000\002\012\002\000\002\013\003" +
    "\000\002\013\003\000\002\014\005\000\002\017\006\000" +
    "\002\017\005\000\002\020\005\000\002\020\003\000\002" +
    "\016\003\000\002\016\003\000\002\016\003\000\002\015" +
    "\003\000\002\015\003\000\002\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\004\004\005\001\002\000\004\002\073\001" +
    "\002\000\004\020\006\001\002\000\010\014\ufffe\021\ufffe" +
    "\022\ufffe\001\002\000\010\014\ufff0\021\ufff0\022\010\001" +
    "\002\000\010\011\026\013\044\016\045\001\002\000\010" +
    "\014\uffff\021\uffff\022\uffff\001\002\000\010\014\ufffd\021" +
    "\ufffd\022\ufffd\001\002\000\006\014\ufff1\021\ufff1\001\002" +
    "\000\006\014\uffef\021\uffef\001\002\000\010\014\ufffc\021" +
    "\ufffc\022\ufffc\001\002\000\006\014\020\021\021\001\002" +
    "\000\006\014\uffee\021\uffee\001\002\000\004\022\023\001" +
    "\002\000\004\005\022\001\002\000\004\002\000\001\002" +
    "\000\006\011\026\016\025\001\002\000\006\014\ufff2\021" +
    "\ufff2\001\002\000\010\017\035\022\033\023\034\001\002" +
    "\000\006\022\030\023\027\001\002\000\006\014\uffe5\021" +
    "\uffe5\001\002\000\010\014\uffe4\016\025\021\uffe4\001\002" +
    "\000\006\014\uffed\021\uffed\001\002\000\006\014\uffe3\021" +
    "\uffe3\001\002\000\010\015\uffe7\016\025\017\uffe7\001\002" +
    "\000\006\015\uffe8\017\uffe8\001\002\000\012\014\uffeb\015" +
    "\uffeb\017\uffeb\021\uffeb\001\002\000\006\015\041\017\042" +
    "\001\002\000\006\015\uffe9\017\uffe9\001\002\000\006\015" +
    "\uffe6\017\uffe6\001\002\000\006\022\033\023\034\001\002" +
    "\000\012\014\uffec\015\uffec\017\uffec\021\uffec\001\002\000" +
    "\006\015\uffea\017\uffea\001\002\000\010\006\070\007\067" +
    "\010\066\001\002\000\010\017\050\022\046\023\034\001" +
    "\002\000\012\013\064\015\uffe7\016\025\017\uffe7\001\002" +
    "\000\006\015\055\017\056\001\002\000\010\012\052\014" +
    "\uffeb\021\uffeb\001\002\000\006\015\ufff4\017\ufff4\001\002" +
    "\000\006\022\030\023\027\001\002\000\004\014\054\001" +
    "\002\000\010\014\ufff6\021\ufff6\022\ufff6\001\002\000\004" +
    "\022\062\001\002\000\004\012\057\001\002\000\006\022" +
    "\030\023\027\001\002\000\004\014\061\001\002\000\010" +
    "\014\ufff7\021\ufff7\022\ufff7\001\002\000\004\013\064\001" +
    "\002\000\006\015\ufff5\017\ufff5\001\002\000\010\006\070" +
    "\007\067\010\066\001\002\000\006\015\ufff3\017\ufff3\001" +
    "\002\000\010\014\ufff8\015\ufff8\017\ufff8\001\002\000\010" +
    "\014\ufff9\015\ufff9\017\ufff9\001\002\000\010\014\ufffa\015" +
    "\ufffa\017\ufffa\001\002\000\004\014\072\001\002\000\010" +
    "\014\ufffb\021\ufffb\022\ufffb\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\071\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\006\001\001\000\020\005\010" +
    "\006\011\007\014\012\015\013\012\014\013\017\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\013\023\014\013" +
    "\017\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\016\036\017\037" +
    "\020\035\001\001\000\006\015\030\017\031\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\016\042\017\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\070\001\001\000\014\010\050" +
    "\011\046\016\036\017\037\020\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\015\052\017\031\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\062\001\001\000\002\001\001" +
    "\000\006\015\057\017\031\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser_g4$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser_g4$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser_g4$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private EnvManager env = new EnvManager();
    
    public void report_error(String message, Object info) {
        System.out.print(message);
    }
    
    public void syntax_error(Symbol cur_token) {
        report_error("Sintaksna greska u liniji " + (cur_token.left + 1) + ": ", cur_token);
        System.out.println("Token '" + cur_token.value + "' nije ocekivan.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser_g4$actions {
  private final parser_g4 parser;

  /** Constructor */
  CUP$parser_g4$actions(parser_g4 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser_g4$do_action(
    int                        CUP$parser_g4$act_num,
    java_cup.runtime.lr_parser CUP$parser_g4$parser,
    java.util.Stack            CUP$parser_g4$stack,
    int                        CUP$parser_g4$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser_g4$result;

      /* select the action based on the action number */
      switch (CUP$parser_g4$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Expression ::= FunctionCall 
            {
              Expression RESULT = null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		FunctionCall fc = (FunctionCall)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                RESULT = fc;
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(11/*Expression*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Expression ::= ID 
            {
              Expression RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                RESULT = new VariableExpression((String)id);
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(11/*Expression*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Expression ::= CONST 
            {
              Expression RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                RESULT = new ConstantExpression((String)c);
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(11/*Expression*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Arg ::= FunctionCall 
            {
              Expression RESULT = null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		FunctionCall fc = (FunctionCall)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
        RESULT = fc;
     
              CUP$parser_g4$result = new java_cup.runtime.Symbol(12/*Arg*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Arg ::= ID 
            {
              Expression RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
        RESULT = new VariableExpression((String)id);
     
              CUP$parser_g4$result = new java_cup.runtime.Symbol(12/*Arg*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Arg ::= CONST 
            {
              Expression RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
        RESULT = new ConstantExpression((String)c);
     
              CUP$parser_g4$result = new java_cup.runtime.Symbol(12/*Arg*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Arguments ::= Arg 
            {
              List RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Expression a = (Expression)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 List l = new ArrayList(); l.add(a); RESULT = l; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(14/*Arguments*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Arguments ::= Arguments COMMA Arg 
            {
              List RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		List a = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		int new_aleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int new_aright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Expression new_a = (Expression)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
               a.add(new_a);
               RESULT = a;
            
              CUP$parser_g4$result = new java_cup.runtime.Symbol(14/*Arguments*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // FunctionCall ::= ID LPAREN RPAREN 
            {
              FunctionCall RESULT = null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		 
                  List<Expression> argList = new ArrayList();
                  RESULT = new FunctionCall((String)fname, argList);
               
              CUP$parser_g4$result = new java_cup.runtime.Symbol(13/*FunctionCall*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // FunctionCall ::= ID LPAREN Arguments RPAREN 
            {
              FunctionCall RESULT = null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		List args = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		 
                  List<Expression> argList = args != null ? (List<Expression>) args : new ArrayList();
                  RESULT = new FunctionCall((String)fname, argList);
               
              CUP$parser_g4$result = new java_cup.runtime.Symbol(13/*FunctionCall*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Assignment ::= ID ASSIGN Expression 
            {
              AssignmentStatement RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Expression expr = (Expression)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                RESULT = new AssignmentStatement((String)id, expr);
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(10/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Statement ::= FunctionCall 
            {
              Statement RESULT = null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		FunctionCall fc = (FunctionCall)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 RESULT = new ExpressionStatement(fc); 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(9/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Statement ::= Assignment 
            {
              Statement RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		AssignmentStatement a = (AssignmentStatement)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 RESULT = a; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(9/*Statement*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Statements ::= 
            {
              List RESULT = null;
		 RESULT = new ArrayList(); 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(8/*Statements*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Statements ::= Statement 
            {
              List RESULT = null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Statement stmt = (Statement)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 List l = new ArrayList(); if (stmt != null) l.add(stmt); RESULT = l; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(8/*Statements*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Statements ::= Statements SEMICOLON Statement 
            {
              List RESULT = null;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		List stmts = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		int new_stmtleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int new_stmtright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Statement new_stmt = (Statement)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                if (new_stmt != null) stmts.add(new_stmt);
                RESULT = stmts;
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(8/*Statements*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Parameter ::= ID COLON Type 
            {
              Parameter RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
               RESULT = new Parameter((String)id, (String)t);
            
              CUP$parser_g4$result = new java_cup.runtime.Symbol(6/*Parameter*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Parameters ::= Parameter 
            {
              List RESULT = null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Parameter p = (Parameter)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 List l = new ArrayList(); l.add(p); RESULT = l; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(7/*Parameters*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Parameters ::= Parameters COMMA Parameter 
            {
              List RESULT = null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		List p = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		int new_pleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int new_pright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		Parameter new_p = (Parameter)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                p.add(new_p);
                RESULT = p;
             
              CUP$parser_g4$result = new java_cup.runtime.Symbol(7/*Parameters*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // FuncDecl ::= ID LPAREN RPAREN ARROW Expression SEMICOLON 
            {
              FunctionDeclaration RESULT = null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-5)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-5)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-5)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		Expression body = (Expression)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		 
              List<Parameter> paramList = new ArrayList();
              FunctionDeclaration fd = new FunctionDeclaration((String)fname, paramList, body);
              RESULT = fd;
           
              CUP$parser_g4$result = new java_cup.runtime.Symbol(5/*FuncDecl*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // FuncDecl ::= ID LPAREN Parameters RPAREN ARROW Expression SEMICOLON 
            {
              FunctionDeclaration RESULT = null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-6)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-6)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-6)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-4)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-4)).right;
		List params = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-4)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		Expression body = (Expression)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		 
              List<Parameter> paramList = params != null ? (List<Parameter>) params : new ArrayList();
              FunctionDeclaration fd = new FunctionDeclaration((String)fname, paramList, body);
              RESULT = fd;
           
              CUP$parser_g4$result = new java_cup.runtime.Symbol(5/*FuncDecl*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= CHAR 
            {
              String RESULT = null;
		 RESULT = "char"; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(15/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= FLOAT 
            {
              String RESULT = null;
		 RESULT = "float"; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(15/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Type ::= INT 
            {
              String RESULT = null;
		 RESULT = "int"; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(15/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VarDecl ::= ID COLON Type SEMICOLON 
            {
              VariableDeclaration RESULT = null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		 
             RESULT = new VariableDeclaration((String)id, (String)t);
          
              CUP$parser_g4$result = new java_cup.runtime.Symbol(4/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declaration ::= FuncDecl 
            {
              List RESULT = null;
		int fdleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int fdright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		FunctionDeclaration fd = (FunctionDeclaration)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 List l = new ArrayList(); l.add(fd); RESULT = l; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(3/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Declaration ::= VarDecl 
            {
              List RESULT = null;
		int vdleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int vdright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		VariableDeclaration vd = (VariableDeclaration)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 List l = new ArrayList(); l.add(vd); RESULT = l; 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(3/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Declarations ::= 
            {
              List RESULT = null;
		 RESULT = new ArrayList(); 
              CUP$parser_g4$result = new java_cup.runtime.Symbol(2/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Declarations ::= Declarations Declaration 
            {
              List RESULT = null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		List d = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		int new_dleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).left;
		int new_dright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right;
		List new_d = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).value;
		 
                  if (d == null) d = new ArrayList();
                  if (new_d != null) {
                      if (new_d instanceof List) {
                          d.addAll((List) new_d);
                      } else {
                          d.add(new_d);
                      }
                  }
                  RESULT = d;
               
              CUP$parser_g4$result = new java_cup.runtime.Symbol(2/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= PROGRAM LBRACE Declarations Statements RBRACE END 
            {
              Program RESULT = null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).right;
		List decls = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-3)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).right;
		List stmts = (List)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-2)).value;
		 
             AST.Program prog = new AST.Program();
             
             // Dodaj deklaracije varijabli
             if (decls != null) {
                 for (Object d : decls) {
                     if (d instanceof VariableDeclaration) {
                         VariableDeclaration vd = (VariableDeclaration) d;
                         prog.addVariable(vd);
                     } else if (d instanceof FunctionDeclaration) {
                         FunctionDeclaration fd = (FunctionDeclaration) d;
                         prog.addFunction(fd);
                     }
                 }
             }
             
             // Dodaj izjave
             if (stmts != null) {
                 for (Object s : stmts) {
                     if (s instanceof Statement) {
                         prog.addStatement((Statement) s);
                     }
                 }
             }
             
             RESULT = prog;
          
              CUP$parser_g4$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          return CUP$parser_g4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).value;
		RESULT = start_val;
              CUP$parser_g4$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_g4$stack.elementAt(CUP$parser_g4$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser_g4$parser.done_parsing();
          return CUP$parser_g4$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

