
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 11 21:41:59 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Sun Jan 11 21:41:59 CET 2026
  */
public class parser_err extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser_err() {super();}

  /** Constructor which sets the default scanner. */
  public parser_err(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\003\005\000\002\003" +
    "\005\000\002\004\004\000\002\005\004\000\002\005\003" +
    "\000\002\005\004\000\002\006\005\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\010\005\000\002" +
    "\010\003\000\002\010\005\000\002\011\003\000\002\011" +
    "\003\000\002\012\005\000\002\012\005\000\002\013\005" +
    "\000\002\013\005\000\002\013\003\000\002\014\003\000" +
    "\002\014\003\000\002\015\012\000\002\015\012\000\002" +
    "\016\005\000\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\063\000\004\004\005\001\002\000\004\002\065\001" +
    "\002\000\012\003\010\006\015\007\014\010\013\001\002" +
    "\000\014\006\ufffc\007\ufffc\010\ufffc\011\ufffc\023\ufffc\001" +
    "\002\000\004\023\063\001\002\000\004\017\062\001\002" +
    "\000\006\003\060\005\061\001\002\000\014\006\015\007" +
    "\014\010\013\011\017\023\022\001\002\000\004\023\ufff7" +
    "\001\002\000\004\023\ufff8\001\002\000\004\023\ufff9\001" +
    "\002\000\010\003\ufff3\005\ufff3\017\ufff3\001\002\000\004" +
    "\023\042\001\002\000\014\006\ufffd\007\ufffd\010\ufffd\011" +
    "\ufffd\023\ufffd\001\002\000\010\003\ufff5\005\ufff5\017\ufff5" +
    "\001\002\000\004\016\030\001\002\000\010\003\ufffe\005" +
    "\ufffe\017\025\001\002\000\010\003\ufff2\005\ufff2\017\ufff2" +
    "\001\002\000\010\003\026\011\017\023\022\001\002\000" +
    "\010\003\ufff4\005\ufff4\017\ufff4\001\002\000\010\003\ufff6" +
    "\005\ufff6\017\ufff6\001\002\000\010\003\034\023\031\024" +
    "\032\001\002\000\014\003\uffeb\005\uffeb\014\uffeb\015\uffeb" +
    "\017\uffeb\001\002\000\014\003\uffec\005\uffec\014\uffec\015" +
    "\uffec\017\uffec\001\002\000\014\003\uffed\005\uffed\014\uffed" +
    "\015\uffed\017\uffed\001\002\000\010\003\ufff0\005\ufff0\017" +
    "\ufff0\001\002\000\014\003\ufff1\005\ufff1\014\036\015\037" +
    "\017\ufff1\001\002\000\006\023\031\024\032\001\002\000" +
    "\006\023\031\024\032\001\002\000\014\003\uffee\005\uffee" +
    "\014\uffee\015\uffee\017\uffee\001\002\000\014\003\uffef\005" +
    "\uffef\014\uffef\015\uffef\017\uffef\001\002\000\004\012\043" +
    "\001\002\000\004\021\044\001\002\000\006\003\046\023" +
    "\045\001\002\000\006\020\uffe7\022\uffe7\001\002\000\004" +
    "\022\055\001\002\000\006\020\050\022\051\001\002\000" +
    "\004\023\054\001\002\000\004\013\052\001\002\000\006" +
    "\011\017\023\022\001\002\000\010\003\uffea\005\uffea\017" +
    "\uffea\001\002\000\006\020\uffe8\022\uffe8\001\002\000\004" +
    "\013\056\001\002\000\006\011\017\023\022\001\002\000" +
    "\010\003\uffe9\005\uffe9\017\uffe9\001\002\000\004\002\uffff" +
    "\001\002\000\004\002\000\001\002\000\014\006\ufffb\007" +
    "\ufffb\010\ufffb\011\ufffb\023\ufffb\001\002\000\004\017\064" +
    "\001\002\000\014\006\ufffa\007\ufffa\010\ufffa\011\ufffa\023" +
    "\ufffa\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\063\000\004\003\003\001\001\000\002\001\001\000" +
    "\012\004\010\005\011\006\005\007\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\006\017\007\006\010\022\011\020\012\015" +
    "\015\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\011\026\012\015\015\023" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\034\014\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\040\001\001\000\004\014\037\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\052\012\015\015\023\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\011" +
    "\056\012\015\015\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser_err$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser_err$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser_err$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        System.err.println("Sintaksna greska: Neocekivan token '" + cur_token.value + 
            "' na liniji " + (cur_token.left + 1) + ", kolona " + (cur_token.right + 1));
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser_err$actions {
  private final parser_err parser;

  /** Constructor */
  CUP$parser_err$actions(parser_err parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser_err$do_action(
    int                        CUP$parser_err$act_num,
    java_cup.runtime.lr_parser CUP$parser_err$parser,
    java.util.Stack            CUP$parser_err$stack,
    int                        CUP$parser_err$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser_err$result;

      /* select the action based on the action number */
      switch (CUP$parser_err$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // NameList ::= ID 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NameList ::= NameList COMMA ID 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(12/*NameList*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ApplyExpression ::= FOR ID IN LBRACKET error RBRACKET APPLY Expression 
            {
              Object RESULT = null;
		 System.err.println("Greska u listi unutar [ ]."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-7)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ApplyExpression ::= FOR ID IN LBRACKET NameList RBRACKET APPLY Expression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(11/*ApplyExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-7)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // TermExpression ::= ID 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(10/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // TermExpression ::= CONST 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(10/*TermExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ArithmeticExpression ::= TermExpression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ArithmeticExpression ::= ArithmeticExpression MINUS TermExpression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ArithmeticExpression ::= ArithmeticExpression PLUS TermExpression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(9/*ArithmeticExpression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Assignment ::= ID ASSIGN error 
            {
              Object RESULT = null;
		 System.err.println("Greska u desnoj strani dodele."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Assignment ::= ID ASSIGN ArithmeticExpression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Expression ::= ApplyExpression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Expression ::= Assignment 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(7/*Expression*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Expressions ::= Expressions SEMICOLON error 
            {
              Object RESULT = null;
		 System.err.println("Greska u izrazu."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Expressions ::= Expression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Expressions ::= Expressions SEMICOLON Expression 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(6/*Expressions*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Type ::= BOOL 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= FLOAT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(5/*Type*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declaration ::= Type ID SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(4/*Declaration*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Declarations ::= error SEMICOLON 
            {
              Object RESULT = null;
		 System.err.println("Greska u deklaraciji."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Declarations ::= Declaration 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Declarations ::= Declarations Declaration 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Block ::= Declarations Expressions 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= MAIN Block error 
            {
              Object RESULT = null;
		 System.err.println("Greska: Nedostaje 'exit'."); 
              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= MAIN Block EXIT 
            {
              Object RESULT = null;

              CUP$parser_err$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          return CUP$parser_err$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).value;
		RESULT = start_val;
              CUP$parser_err$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser_err$stack.elementAt(CUP$parser_err$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser_err$parser.done_parsing();
          return CUP$parser_err$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

