
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 01 22:33:41 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 19;
  public static final int ELSE = 15;
  public static final int PLUS = 16;
  public static final int OR = 18;
  public static final int CHAR = 11;
  public static final int SEMI = 6;
  public static final int WHILE = 14;
  public static final int LEFTPAR = 23;
  public static final int END = 4;
  public static final int RIGHTPAR = 24;
  public static final int COLON = 5;
  public static final int ID = 25;
  public static final int LE = 20;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int BOOLEAN = 13;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int GE = 22;
  public static final int CONST = 26;
  public static final int error = 1;
  public static final int DOT = 8;
  public static final int EQ = 21;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 10;
  public static final int REAL = 12;
  public static final int MUL = 17;
}

