
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 09 08:58:47 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Fri Jan 09 08:58:47 CET 2026
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\021\000\002\002\004\000\002\003\017\000\002\003" +
    "\017\000\002\003\017\000\002\003\011\000\002\004\003" +
    "\000\002\004\006\000\002\004\006\000\002\004\004\000" +
    "\002\005\004\000\002\006\005\000\002\006\002\000\002" +
    "\007\004\000\002\010\005\000\002\010\002\000\002\011" +
    "\003\000\002\011\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\004\011\005\001\002\000\004\002\071\001" +
    "\002\000\004\015\006\001\002\000\010\003\012\013\007" +
    "\014\010\001\002\000\012\016\ufff2\021\ufff2\024\ufff2\025" +
    "\ufff2\001\002\000\012\016\ufff1\021\ufff1\024\ufff1\025\ufff1" +
    "\001\002\000\012\016\ufff3\021\ufff3\024\ufff3\025\065\001" +
    "\002\000\004\016\053\001\002\000\004\016\021\001\002" +
    "\000\010\016\ufff6\021\ufff6\024\016\001\002\000\006\016" +
    "\ufff8\021\ufff8\001\002\000\006\013\007\014\010\001\002" +
    "\000\010\016\ufff6\021\ufff6\024\016\001\002\000\006\016" +
    "\ufff7\021\ufff7\001\002\000\004\017\022\001\002\000\010" +
    "\003\024\011\005\013\023\001\002\000\004\023\046\001" +
    "\002\000\006\020\045\021\040\001\002\000\004\012\027" +
    "\001\002\000\006\012\ufffc\020\ufffc\001\002\000\004\015" +
    "\030\001\002\000\010\003\031\013\007\014\010\001\002" +
    "\000\004\016\041\001\002\000\004\016\033\001\002\000" +
    "\004\021\034\001\002\000\010\003\035\011\005\013\023" +
    "\001\002\000\004\021\040\001\002\000\004\020\037\001" +
    "\002\000\010\002\000\012\000\020\000\001\002\000\006" +
    "\012\ufff9\020\ufff9\001\002\000\004\021\042\001\002\000" +
    "\010\003\035\011\005\013\023\001\002\000\004\020\044" +
    "\001\002\000\010\002\ufffe\012\ufffe\020\ufffe\001\002\000" +
    "\010\002\ufffd\012\ufffd\020\ufffd\001\002\000\010\003\047" +
    "\013\007\014\010\001\002\000\004\021\052\001\002\000" +
    "\004\021\051\001\002\000\006\012\ufffb\020\ufffb\001\002" +
    "\000\006\012\ufffa\020\ufffa\001\002\000\004\017\054\001" +
    "\002\000\010\003\035\011\005\013\023\001\002\000\004" +
    "\012\056\001\002\000\004\015\057\001\002\000\006\013" +
    "\007\014\010\001\002\000\004\016\061\001\002\000\004" +
    "\021\062\001\002\000\010\003\035\011\005\013\023\001" +
    "\002\000\004\020\064\001\002\000\010\002\uffff\012\uffff" +
    "\020\uffff\001\002\000\006\013\007\014\010\001\002\000" +
    "\010\016\ufff5\021\ufff5\024\ufff5\001\002\000\012\016\ufff3" +
    "\021\ufff3\024\ufff3\025\065\001\002\000\010\016\ufff4\021" +
    "\ufff4\024\ufff4\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\067\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\005\012\007\013\011\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\065\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\014" +
    "\001\001\000\002\001\001\000\006\007\016\011\010\001" +
    "\001\000\004\006\017\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\025\004\024\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\005\031\007\013\011\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\025\004\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\025\004\042\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\005\047" +
    "\007\013\011\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\025\004\054\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\005\057\007\013\011\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\003\025\004" +
    "\062\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\066\001\001\000\002\001\001\000\004\010\067\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  public void report_error(String message, Object info) {
    if (info instanceof Symbol) {
      Symbol s = (Symbol) info;
      System.err.println("SINTAKSNA GRESKA: " + message +
        " (linija " + s.left + ", kolona " + s.right + ")");
      return;
    }
    System.err.println("SINTAKSNA GRESKA: " + message);
  }

  public void report_fatal_error(String message, Object info) throws Exception {
    report_error(message, info);
    throw new RuntimeException(message);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Term ::= CONST 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Term ::= ID 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // AndExpressionTail ::= 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*AndExpressionTail*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // AndExpressionTail ::= AND Term AndExpressionTail 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*AndExpressionTail*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // AndExpression ::= Term AndExpressionTail 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*AndExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // ExpressionTail ::= 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*ExpressionTail*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ExpressionTail ::= OR AndExpression ExpressionTail 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*ExpressionTail*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Expression ::= AndExpression ExpressionTail 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Statement ::= error SEMICOLON 
            {
              Object RESULT = null;
		 parser.report_error("Neispravna naredba, preskacem do ';'", null); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Statement ::= ID ASSIGN error SEMICOLON 
            {
              Object RESULT = null;
		 parser.report_error("Neispravan izraz u dodeli, preskacem do ';'", null); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Statement ::= ID ASSIGN Expression SEMICOLON 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Statement ::= RedoLoop 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // RedoLoop ::= LOOP LPAREN Expression RPAREN LBRACE error RBRACE 
            {
              Object RESULT = null;
		 parser.report_error("Greska u LOOP bloku, preskacem do '}'", null); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*RedoLoop*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // RedoLoop ::= LOOP LPAREN Expression RPAREN LBRACE Statement REDO LPAREN error RPAREN SEMICOLON Statement RBRACE 
            {
              Object RESULT = null;
		 parser.report_error("Neispravan uslov u REDO(...), preskacem do ')'", null); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*RedoLoop*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-12)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // RedoLoop ::= LOOP LPAREN error RPAREN LBRACE Statement REDO LPAREN Expression RPAREN SEMICOLON Statement RBRACE 
            {
              Object RESULT = null;
		 parser.report_error("Neispravan uslov u LOOP(...), preskacem do ')'", null); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*RedoLoop*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-12)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // RedoLoop ::= LOOP LPAREN Expression RPAREN LBRACE Statement REDO LPAREN Expression RPAREN SEMICOLON Statement RBRACE 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*RedoLoop*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-12)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= RedoLoop EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

