
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 09 08:58:47 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 19;
  public static final int NE = 25;
  public static final int LT = 20;
  public static final int SEMICOLON = 15;
  public static final int OR = 18;
  public static final int RBRACE = 14;
  public static final int RPAREN = 12;
  public static final int INT = 3;
  public static final int CHAR = 4;
  public static final int LOOP = 7;
  public static final int GT = 21;
  public static final int LPAREN = 11;
  public static final int LBRACE = 13;
  public static final int LE = 22;
  public static final int ID = 9;
  public static final int COMMA = 16;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int GE = 23;
  public static final int CONST = 10;
  public static final int error = 1;
  public static final int EQ = 24;
  public static final int ASSIGN = 17;
  public static final int BOOL = 6;
  public static final int REDO = 8;
}

